# Generated by Django 5.0.2 on 2025-04-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('pros', models.TextField()),
                ('cons', models.TextField()),
                ('overview', models.TextField()),
                ('five_star_percentage', models.FloatField()),
                ('four_star_percentage', models.FloatField()),
                ('three_star_percentage', models.FloatField()),
                ('two_star_percentage', models.FloatField()),
                ('one_star_percentage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
